"""Run Projects One and Three end to end from fresh random trials."""
import argparse,json,subprocess,sys,time
from pathlib import Path

def main():
    a=argparse.ArgumentParser(description=__doc__);a.add_argument('--profile',choices=['quick','full'],default='quick');a.add_argument('--out',type=Path,default=Path('fresh-study'));a.add_argument('--seed',type=int,default=20260928);a.add_argument('--sat-seconds',type=float);a.add_argument('--sat-repeats',type=int);args=a.parse_args()
    root=Path(__file__).resolve().parent;out=args.out.resolve();out.mkdir(parents=True,exist_ok=True)
    reps=args.sat_repeats if args.sat_repeats is not None else (3 if args.profile=='quick' else 20)
    seconds=args.sat_seconds if args.sat_seconds is not None else (.5 if args.profile=='quick' else 5.)
    def run(name,*argv):
        cmd=[sys.executable,str(root/name),*map(str,argv)];print('\nRunning',name,flush=True);subprocess.run(cmd,check=True)
    started=time.monotonic()
    run('distributions.py','--out',out/'distributions','--trials',100 if args.profile=='quick' else 2000,'--seed',args.seed)
    run('plot_distributions.py','--input',out/'distributions')
    growth_cmd=['--profile',args.profile,'--out',out/'monte_carlo','--seed',args.seed]
    if args.profile=='quick':growth_cmd.extend(['--max-n-growth',30,'--max-n-threshold',35,'--max-k-threshold',7])
    run('experiments.py',*growth_cmd)
    run('plot.py','--input',out/'monte_carlo')
    run('export_cnf.py','--n',13,'--k',4,'--out',out/'sat'/'K13_no_K4.cnf')
    run('solver_survey.py','--n',13,'--seconds',seconds,'--out',out/'sat'/'solver_survey')
    run('sat_compare.py','--min-n',10,'--max-n',17,'--repeats',reps,'--seconds',seconds,'--seed',args.seed,'--out',out/'sat')
    run('plot_compare.py','--input',out/'sat')
    (out/'run_manifest.json').write_text(json.dumps(dict(profile=args.profile,seed=args.seed,sat_repeats=reps,sat_seconds_per_run=seconds,elapsed_seconds=round(time.monotonic()-started,3),note='All results and figures in this folder were generated by this invocation, not copied from the paper.'),indent=2)+'\n')
    print('Complete. Fresh results:',out,flush=True)
if __name__=='__main__':main()
